name: Buf checkup
on: pull_request
permissions:
  contents: read
  pull-requests: write
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: run buf
        uses: bufbuild/buf-action@v1
        with: 
          breaking: false
