name: Generate go code
on:
  push:
    branches:
      - master
    paths:
      - 'dictybase/**/*.proto'
      - 'buf.gen.yaml'
      - 'buf.yaml'
      - '.github/workflows/*.yml'
permissions: 
  contents: read
  pages: write
  id-token: write
concurrency: 
  group: "pages"
  cancel-in-progress: false

jobs:
  generate:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: generate
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: setup buf
        uses: bufbuild/buf-action@v1
        with: 
          version: 1.47.2
          setup_only: true
      - name: generate code
        run: |
            buf generate
      - name: configure git
        run: |
            git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --global user.name "$GITHUB_ACTOR"
      - name: checkout target repo
        if: success()
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: dictybase/go-genproto
          path: target
      - name: add git config
        run: |
          git config --local user.email "dictybasebot@users.noreply.github.com"
          git config --local user.name "dictybasebot"
      - name: copy generated files
        run: |
          rm -rf target/dictybaseapis
          cp -r generated/github.com/dictyBase/go-genproto/dictybaseapis target
          cd target
          git add .
          git diff-index --quiet HEAD || git commit -m "update on `date +"%m-%d-%Y:%H:%M:%S"`"
      - name: get short sha
        id: vars
        run: |
          sha=$(git rev-parse --short HEAD)
          echo ::set-output name=id::${sha}
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          branch: chore/update-${{ steps.vars.outputs.id }}
          directory: ./target
          repository: dictybase/go-genproto
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: docs/index.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
