name: Buf Lint
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  buf:
    name: Buf build and lint
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: download and setup path for buf binary
        run: |
          mkdir -p buf/bin
          curl -L -o buf/bin/buf https://github.com/bufbuild/buf/releases/download/v0.42.1/buf-Linux-x86_64
          chmod +x buf/bin/buf
          echo "$GITHUB_WORKSPACE/buf/bin" >> $GITHUB_PATH
      - name: run buf build
        run: buf build
      - name: run buf lint
        run: buf lint