name: Buf
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up golang
        uses: actions/setup-go@v2
        with:
            go-version: "^1.16.3"
      - name: install necessary binaries
        run: make install
      - name: lint
        run: make lint
  generate:
    name: Generate Go code
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up golang
        uses: actions/setup-go@v2
        with:
            go-version: "^1.16.3"
      - name: install necessary binaries
        run: make install
      - name: generate go code
        run: make generate